### ISSUE TITLE
Unexpected lvalue type: Number stack traceback

### ISSUE THREAD

**Issue by teca44** [zeusssz/hercules-obfuscator#31] opened 2024-12-04 01:32 UTC
`
lua: ...reter/LuaInterpreter/Parser/SyntaxParsers/Statements.lua:69: Unexpected lvalue type: Number
stack traceback:
        [C]: in function 'error'
        ...reter/LuaInterpreter/Parser/SyntaxParsers/Statements.lua:69: in function 'Interpreter/LuaInterpreter/Parser/SyntaxParsers/Statements.parseFunctionCallOrVariableAssignment'
        ...../Compiler/Interpreter/LuaInterpreter/Parser/Parser.lua:140: in method 'getNextNode'
        ...../Compiler/Interpreter/LuaInterpreter/Parser/Parser.lua:151: in method 'consumeCodeBlock'
        ...../Compiler/Interpreter/LuaInterpreter/Parser/Parser.lua:188: in method 'parse'
        .\modules/Compiler/../Compiler/api.lua:59: in field 'ConvertToAST'
        .\modules/Compiler/../Compiler/api.lua:159: in function <.\modules/Compiler/../Compiler/api.lua:156>
        (...tail calls...)
        .\pipeline.lua:58: in function 'pipeline.process'
        hercules.lua:294: in main chunk
        [C]: in ?
`

how do i fix that?
OS: Windows 11

**Comment by zeusssz** [comment] 2024-12-04 09:13
are you running Lua 5.4?

**Comment by shimms** [comment] 2024-12-04 09:34
I too get this error on 5.4, works as expected on 5.1.

**Comment by zeusssz** [comment] 2024-12-04 10:26
@teca44 send me the original file, if youre comfortable. it will help me in assessing the root cause of the issue

**Comment by teca44** [comment] 2024-12-04 14:01
> are you running Lua 5.4?

yes

**Comment by teca44** [comment] 2024-12-04 22:45
@shimms Still the same error with lua 5.1.4
`
lua51: ...r/LuaInterpreter/Parser/SyntaxParsers/Statements.lua:69: Unexpected lvalue type: Number
stack traceback:
        [C]: in function 'error'
        ...r/LuaInterpreter/Parser/SyntaxParsers/Statements.lua:69: in function 'parseFunctionCallOrVariableAssignment'
        ...ompiler/Interpreter/LuaInterpreter/Parser/Parser.lua:140: in function 'getNextNode'
        ...ompiler/Interpreter/LuaInterpreter/Parser/Parser.lua:151: in function 'consumeCodeBlock'
        ...ter/LuaInterpreter/Parser/SyntaxParsers/Keywords.lua:108: in function 'keywordFunction'
        ...ompiler/Interpreter/LuaInterpreter/Parser/Parser.lua:134: in function 'getNextNode'
        ...ompiler/Interpreter/LuaInterpreter/Parser/Parser.lua:151: in function 'consumeCodeBlock'
        ...ompiler/Interpreter/LuaInterpreter/Parser/Parser.lua:188: in function 'parse'
        .\modules/Compiler/../Compiler/api.lua:59: in function 'ConvertToAST'
        .\modules/Compiler/../Compiler/api.lua:159: in function <.\modules/Compiler/../Compiler/api.lua:156>
        (tail call): ?
        .\pipeline.lua:58: in function 'process'
        hercules.lua:294: in main chunk
        [C]: ?
`

**Comment by zeusssz** [comment] 2024-12-05 09:58
@teca44 what file are you obfuscating. sharing the source might help get to the root of the issue. feel free to contact me on discord

**Comment by zeusssz** [comment] 2024-12-05 12:36
nevermind, this issue should be fixed
@shimms @teca44

**Closed by zeusssz** 2024-12-05 12:36 UTC
